import { randomUUID } from "node:crypto";
import { existsSync, renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
	checkedDirectory,
	checkedRegular,
} from "../../../lina-core/src/attachments/filesystem.ts";

/** This generated home belongs to Lina. Global Codex configuration is read-only. */
export function provisionCodexHome(
	stateRoot: string,
	connection: {
		providerTable: string;
		catalogJson: string | null;
	},
): string {
	const home = checkedDirectory(join(stateRoot, "codex-home"), true);
	const write = (name: string, value: string) => {
		const path = join(home, name);
		if (existsSync(path)) checkedRegular(path);
		const temp = join(home, `.${name}.${randomUUID()}`);
		writeFileSync(temp, value, { mode: 0o600, flag: "wx" });
		renameSync(temp, path);
	};
	const catalog = join(home, "opencodex-catalog.json");
	if (connection.catalogJson)
		write("opencodex-catalog.json", connection.catalogJson);
	const config = [
		"# Generated by Lina from OpenCodex Hub. Configure providers in OpenCodex.",
		'model_provider = "opencodex"',
		'approval_policy = "on-request"',
		'sandbox_mode = "workspace-write"',
		...(connection.catalogJson
			? [`model_catalog_json = ${JSON.stringify(catalog)}`]
			: []),
		connection.providerTable,
	].join("\n");
	write("config.toml", config);
	return home;
}
